### ISSUE TITLE
Suggestion: Hooking RegEnumValueA

### ISSUE THREAD

**Issue by nckstwrt** [Luca1991/DiscCheckEmu#25]
Now you've done RegQueryValueEx - could you also consider implementing RegEnumValueA in the same way?
(Fifa 2003 uses it to read all its keys and most importantly check its "CD Drive" reg key and then only checks that drive for the disk annoyingly. RegEnumValueA  doesn't use RegQueryValueEx under hood also annoyingly :) )

Many thanks!

**Comment by Luca1991** [comment]
Hi @nckstwrt 
Sure, I can implement a RegEnumValueA hook.
After reading the [MS doc](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regenumvaluea) I think the best way to hook this API is:

1. call the original API fist
2. check if the registry path of the hKey matches with the one specified in the yaml (using reg_utils::getPathFromHKEY function)
3. then, check if lpValueName mateches with the one specified in the yaml
4. if so, spoof the value (specified in the yaml)

A workaround is to simply check the dwIndex parameter and spoof the value based on that without calling the original API at all, but I wouldn't do that, because if the user simply adds another key to that registry path, it won't match anymore .

What do you think about it?

**Comment by nckstwrt** [comment]
Yes absolutely - I think that would work well :)

Will be happy to test and confirm back :)

**Comment by Luca1991** [comment]
Hi @nckstwrt
good news: I just finished implementing the hook.
I want to double check everything before pushing the code.
I hope it will be ready tomorrow evening/night.

**Comment by Luca1991** [comment]
Hi @nckstwrt 
RegEnumValueA hook is now available in master.
The usage, from a configuration perspective, is identical to RegQueryValueExA.

I'll wait for your test and feedback, thanks.

**Comment by Luca1991** [comment]
Hi @nckstwrt 

> Perfect! :) Worked first time.

YAY! 😄 

> (I'll do a pull request at such stage for the configs I've made so far - once I've cleaned them up)

Great! Thank you very much, I'm looking forward to your PR then!

Ah FYI, as a side note, due to #20 I'm considering moving hooks installation on a separate function, to be called right after the injection. When I'll do that, you can just copy/paste the relevant code from DCELoader and it will just work. 

One last thing: is it fine for you if I mention your SafeDiscLoader in a "Software using this project" section in README.md?

**Comment by nckstwrt** [comment]
Not sure I'd be that worried by #20 - adding complexity to workaround a problem no one is having seems overkill. But easy for me to adapt if you do change :)

> One last thing: is it fine for you if I mention your SafeDiscLoader in a "Software using this project" section in README.md?

Of course :)
